package com.tuhu.springbootmybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class TTrainCourse extends Object implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.id
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.course_name
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.course_content
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    private String courseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.lecturer
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    private String lecturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.opening_time
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date openingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.create_time
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_course.update_time
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    @JsonFormat(locale = "zh", timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * 逻辑删除标记
     */
    private Integer isDelete;


    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }


    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_train_course
     *
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.id
     *
     * @return the value of t_train_course.id
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.id
     *
     * @param id the value for t_train_course.id
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.course_name
     *
     * @return the value of t_train_course.course_name
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.course_name
     *
     * @param courseName the value for t_train_course.course_name
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.course_content
     *
     * @return the value of t_train_course.course_content
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public String getCourseContent() {
        return courseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.course_content
     *
     * @param courseContent the value for t_train_course.course_content
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setCourseContent(String courseContent) {
        this.courseContent = courseContent == null ? null : courseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.lecturer
     *
     * @return the value of t_train_course.lecturer
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public String getLecturer() {
        return lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.lecturer
     *
     * @param lecturer the value for t_train_course.lecturer
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setLecturer(String lecturer) {
        this.lecturer = lecturer == null ? null : lecturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.opening_time
     *
     * @return the value of t_train_course.opening_time
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public Date getOpeningTime() {
        return openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.opening_time
     *
     * @param openingTime the value for t_train_course.opening_time
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setOpeningTime(Date openingTime) {
        this.openingTime = openingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.create_time
     *
     * @return the value of t_train_course.create_time
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.create_time
     *
     * @param createTime the value for t_train_course.create_time
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_course.update_time
     *
     * @return the value of t_train_course.update_time
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_course.update_time
     *
     * @param updateTime the value for t_train_course.update_time
     * @mbggenerated Tue Sep 29 15:05:54 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}