package com.tuhu.springbootmybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class TTrainEntry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.id
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.user_name
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.user_card
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private String userCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.lecturer
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.nationality
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.age
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.body_state
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private Integer bodyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.course_name
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.state
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.reviewer
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private String reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.create_time
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_train_entry.update_time
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date updateTime;


    /**
     * 逻辑删除标记
     */
    private Integer isDelete;


    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.id
     *
     * @return the value of t_train_entry.id
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.id
     *
     * @param id the value for t_train_entry.id
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.user_name
     *
     * @return the value of t_train_entry.user_name
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.user_name
     *
     * @param userName the value for t_train_entry.user_name
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.user_card
     *
     * @return the value of t_train_entry.user_card
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public String getUserCard() {
        return userCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.user_card
     *
     * @param userCard the value for t_train_entry.user_card
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setUserCard(String userCard) {
        this.userCard = userCard == null ? null : userCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.lecturer
     *
     * @return the value of t_train_entry.phone
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.lecturer
     *
     * @param phone the value for t_train_entry.phone
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.nationality
     *
     * @return the value of t_train_entry.nationality
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.nationality
     *
     * @param nationality the value for t_train_entry.nationality
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.age
     *
     * @return the value of t_train_entry.age
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.age
     *
     * @param age the value for t_train_entry.age
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.body_state
     *
     * @return the value of t_train_entry.body_state
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Integer getBodyState() {
        return bodyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.body_state
     *
     * @param bodyState the value for t_train_entry.body_state
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setBodyState(Integer bodyState) {
        this.bodyState = bodyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.course_name
     *
     * @return the value of t_train_entry.course_name
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.course_name
     *
     * @param courseId the value for t_train_entry.course_name
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.state
     *
     * @return the value of t_train_entry.state
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.state
     *
     * @param state the value for t_train_entry.state
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.reviewer
     *
     * @return the value of t_train_entry.reviewer
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.reviewer
     *
     * @param reviewer the value for t_train_entry.reviewer
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.create_time
     *
     * @return the value of t_train_entry.create_time
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.create_time
     *
     * @param createTime the value for t_train_entry.create_time
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_train_entry.update_time
     *
     * @return the value of t_train_entry.update_time
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_train_entry.update_time
     *
     * @param updateTime the value for t_train_entry.update_time
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}