package com.tuhu.springbootmybatis.mapper;

import com.tuhu.springbootmybatis.entity.TTrainEntry;
import com.tuhu.springbootmybatis.vo.TTrainEntryRespGetVO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TTrainEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int insert(TTrainEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int insertSelective(TTrainEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    TTrainEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int updateByPrimaryKeySelective(TTrainEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int updateByPrimaryKey(TTrainEntry record);

    /**
     * 用户课程报名限制5人
     *
     * @param tTrainEntry
     * @return
     */
    int selectEntryCountByCourseId(TTrainEntry tTrainEntry);

    /**
     * 校验是否重复报名 身份证编号+课程名称
     *
     * @param tTrainEntry
     * @return
     */
    int selectEntryByUserCard(TTrainEntry tTrainEntry);

    /**
     * 用户查看自己的报名信息
     *
     * @param
     * @return
     */
    List<TTrainEntryRespGetVO> getEntryByUserCard(String userCard);
}