//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuhu.Service.Activity.Server {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tuhu.Service.Activity.Server.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 获取活动的异常 的本地化字符串。
        /// </summary>
        internal static string Activity_Error {
            get {
                return ResourceManager.GetString("Activity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成短链接失败 的本地化字符串。
        /// </summary>
        internal static string Error_GetQuestionnaireURL_Failure {
            get {
                return ResourceManager.GetString("Error_GetQuestionnaireURL_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兑换卡不足，赶紧竞猜赢卡 的本地化字符串。
        /// </summary>
        internal static string Invalid_Acitivty_CouponInsufficient {
            get {
                return ResourceManager.GetString("Invalid_Acitivty_CouponInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经分享过了 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_AlreadyShare {
            get {
                return ResourceManager.GetString("Invalid_Activity_AlreadyShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动尚未开始 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_DateError {
            get {
                return ResourceManager.GetString("Invalid_Activity_DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 积分规则ID为空 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_Empty_IntegralRuleID {
            get {
                return ResourceManager.GetString("Invalid_Activity_Empty_IntegralRuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项ID为空 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_Empty_OptionID {
            get {
                return ResourceManager.GetString("Invalid_Activity_Empty_OptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID为空 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_Empty_UserId {
            get {
                return ResourceManager.GetString("Invalid_Activity_Empty_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取锁失败 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_Locker {
            get {
                return ResourceManager.GetString("Invalid_Activity_Locker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前商品已经下架，请兑换其他商品 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_NoOnSale {
            get {
                return ResourceManager.GetString("Invalid_Activity_NoOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到该活动 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_NotFound {
            get {
                return ResourceManager.GetString("Invalid_Activity_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到问题 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_NotFound_Question {
            get {
                return ResourceManager.GetString("Invalid_Activity_NotFound_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到问题选项 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_NotFound_QuestionOption {
            get {
                return ResourceManager.GetString("Invalid_Activity_NotFound_QuestionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前库存不足，您可兑换其他产品 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_OutOfStock {
            get {
                return ResourceManager.GetString("Invalid_Activity_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兑换时间已经截止，不能兑换 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_PrizeEndTime {
            get {
                return ResourceManager.GetString("Invalid_Activity_PrizeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兑换奖品设置异常 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_PrizeError {
            get {
                return ResourceManager.GetString("Invalid_Activity_PrizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此兑换物只读 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_PrizeReadOnly {
            get {
                return ResourceManager.GetString("Invalid_Activity_PrizeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复答题 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_RepeatAnswer {
            get {
                return ResourceManager.GetString("Invalid_Activity_RepeatAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间已经截止 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_TimeEnd {
            get {
                return ResourceManager.GetString("Invalid_Activity_TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前商品您已兑换，请兑换其他商品 的本地化字符串。
        /// </summary>
        internal static string Invalid_Activity_UserPrizeExists {
            get {
                return ResourceManager.GetString("Invalid_Activity_UserPrizeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户积分操作异常 的本地化字符串。
        /// </summary>
        internal static string Invalid_Integral {
            get {
                return ResourceManager.GetString("Invalid_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重试 的本地化字符串。
        /// </summary>
        internal static string Invalid_SystemError {
            get {
                return ResourceManager.GetString("Invalid_SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ComplaintsID参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_ComplaintsID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_ComplaintsID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_Department_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_Department_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题{0}为必填项 的本地化字符串。
        /// </summary>
        internal static string ParameterError_IsRequired {
            get {
                return ResourceManager.GetString("ParameterError_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}不符合规则 的本地化字符串。
        /// </summary>
        internal static string ParameterError_NotConformityRule {
            get {
                return ResourceManager.GetString("ParameterError_NotConformityRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderID参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_OrderID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_OrderID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题{0}超出可输入的字符长度 的本地化字符串。
        /// </summary>
        internal static string ParameterError_OverMaxChar {
            get {
                return ResourceManager.GetString("ParameterError_OverMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageID参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_PageID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_PageID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuestionList参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_QuestionList_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_QuestionList_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuestionnaireID参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_QuestionnaireID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_QuestionnaireID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StaffEmail参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_StaffEmail_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_StaffEmail_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserID参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_UserID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_UserID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserPhone参数不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_UserPhone_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_UserPhone_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的问卷已成功提交 的本地化字符串。
        /// </summary>
        internal static string Questionnaire_IsAnswered {
            get {
                return ResourceManager.GetString("Questionnaire_IsAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您访问的问卷不存在 的本地化字符串。
        /// </summary>
        internal static string Questionnaire_NotExist {
            get {
                return ResourceManager.GetString("Questionnaire_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的问卷已过期 的本地化字符串。
        /// </summary>
        internal static string Questionnaire_Overdue {
            get {
                return ResourceManager.GetString("Questionnaire_Overdue", resourceCulture);
            }
        }
    }
}
