server:
  port: 8089

spring:
  datasource:
    username: user_cl_newcomere
    password: Tuhumima123%]
    url: jdbc:mysql://172.16.28.82:3306/tuhu_cl_newcomere?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.tuhu.springbootmybatis.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis生成sql打印

app:
  id: demo-tuhu

apollo:
  meta: http://localhost:8080 # Apollo 中的 Eureka 注册中心地址
  #cluster:  # 指定 Apollo 集群，相同集群实例使用对应集群的配置
  #cacheDir:  # 配置缓存目录，网络不可用时任然可提供配置服务
  bootstrap:
    enable: true # 启用 apollo

env: DEV # 指定环境

logging:
  level:
    com:
      tuhu:
        springbootmybatis:
          mapper : debug #生成sql打印
  file:
    path: D:/ #path的级别比name的级别要低 只有path才能生效  有name时path不生效
    name: springbootmybatis.log
  config: classpath:logging-config.xml