//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuhu.Service.Activity.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tuhu.Service.Activity.Server.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取活动的异常.
        /// </summary>
        internal static string Activity_Error {
            get {
                return ResourceManager.GetString("Activity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成短链接失败.
        /// </summary>
        internal static string Error_GetQuestionnaireURL_Failure {
            get {
                return ResourceManager.GetString("Error_GetQuestionnaireURL_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兑换卡不足，赶紧竞猜赢卡.
        /// </summary>
        internal static string Invalid_Acitivty_CouponInsufficient {
            get {
                return ResourceManager.GetString("Invalid_Acitivty_CouponInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经分享过了.
        /// </summary>
        internal static string Invalid_Activity_AlreadyShare {
            get {
                return ResourceManager.GetString("Invalid_Activity_AlreadyShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动尚未开始.
        /// </summary>
        internal static string Invalid_Activity_DateError {
            get {
                return ResourceManager.GetString("Invalid_Activity_DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分规则ID为空.
        /// </summary>
        internal static string Invalid_Activity_Empty_IntegralRuleID {
            get {
                return ResourceManager.GetString("Invalid_Activity_Empty_IntegralRuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项ID为空.
        /// </summary>
        internal static string Invalid_Activity_Empty_OptionID {
            get {
                return ResourceManager.GetString("Invalid_Activity_Empty_OptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户ID为空.
        /// </summary>
        internal static string Invalid_Activity_Empty_UserId {
            get {
                return ResourceManager.GetString("Invalid_Activity_Empty_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取锁失败.
        /// </summary>
        internal static string Invalid_Activity_Locker {
            get {
                return ResourceManager.GetString("Invalid_Activity_Locker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前商品已经下架，请兑换其他商品.
        /// </summary>
        internal static string Invalid_Activity_NoOnSale {
            get {
                return ResourceManager.GetString("Invalid_Activity_NoOnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到该活动.
        /// </summary>
        internal static string Invalid_Activity_NotFound {
            get {
                return ResourceManager.GetString("Invalid_Activity_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到问题.
        /// </summary>
        internal static string Invalid_Activity_NotFound_Question {
            get {
                return ResourceManager.GetString("Invalid_Activity_NotFound_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到问题选项.
        /// </summary>
        internal static string Invalid_Activity_NotFound_QuestionOption {
            get {
                return ResourceManager.GetString("Invalid_Activity_NotFound_QuestionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前库存不足，您可兑换其他产品.
        /// </summary>
        internal static string Invalid_Activity_OutOfStock {
            get {
                return ResourceManager.GetString("Invalid_Activity_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兑换时间已经截止，不能兑换.
        /// </summary>
        internal static string Invalid_Activity_PrizeEndTime {
            get {
                return ResourceManager.GetString("Invalid_Activity_PrizeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兑换奖品设置异常.
        /// </summary>
        internal static string Invalid_Activity_PrizeError {
            get {
                return ResourceManager.GetString("Invalid_Activity_PrizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此兑换物只读.
        /// </summary>
        internal static string Invalid_Activity_PrizeReadOnly {
            get {
                return ResourceManager.GetString("Invalid_Activity_PrizeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复答题.
        /// </summary>
        internal static string Invalid_Activity_RepeatAnswer {
            get {
                return ResourceManager.GetString("Invalid_Activity_RepeatAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间已经截止.
        /// </summary>
        internal static string Invalid_Activity_TimeEnd {
            get {
                return ResourceManager.GetString("Invalid_Activity_TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前商品您已兑换，请兑换其他商品.
        /// </summary>
        internal static string Invalid_Activity_UserPrizeExists {
            get {
                return ResourceManager.GetString("Invalid_Activity_UserPrizeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动尚未开始或者活动已经结束.
        /// </summary>
        internal static string Invalid_Game_ActivityRunning {
            get {
                return ResourceManager.GetString("Invalid_Game_ActivityRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经分享.
        /// </summary>
        internal static string Invalid_Game_AlreadyShare {
            get {
                return ResourceManager.GetString("Invalid_Game_AlreadyShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已领取过.
        /// </summary>
        internal static string Invalid_Game_AlreadyUserPrizeExists {
            get {
                return ResourceManager.GetString("Invalid_Game_AlreadyUserPrizeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序异常、请重试.
        /// </summary>
        internal static string Invalid_Game_Error {
            get {
                return ResourceManager.GetString("Invalid_Game_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数异常.
        /// </summary>
        internal static string Invalid_Game_ErrorParameter {
            get {
                return ResourceManager.GetString("Invalid_Game_ErrorParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分不足.
        /// </summary>
        internal static string Invalid_Game_ErrorPoint {
            get {
                return ResourceManager.GetString("Invalid_Game_ErrorPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品异常、请重试.
        /// </summary>
        internal static string Invalid_Game_ErrorPrize {
            get {
                return ResourceManager.GetString("Invalid_Game_ErrorPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发放奖品失败、请重试.
        /// </summary>
        internal static string Invalid_Game_ErrorSendPrize {
            get {
                return ResourceManager.GetString("Invalid_Game_ErrorSendPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置信息异常、请重试.
        /// </summary>
        internal static string Invalid_Game_ErrorSetting {
            get {
                return ResourceManager.GetString("Invalid_Game_ErrorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户信息异常、请重试.
        /// </summary>
        internal static string Invalid_Game_ErrorUser {
            get {
                return ResourceManager.GetString("Invalid_Game_ErrorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法提交.
        /// </summary>
        internal static string Invalid_Game_Illegal {
            get {
                return ResourceManager.GetString("Invalid_Game_Illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有奖品了.
        /// </summary>
        internal static string Invalid_Game_NoPrize {
            get {
                return ResourceManager.GetString("Invalid_Game_NoPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该好友今日助力人数已达上限.
        /// </summary>
        internal static string Invalid_Game_NoSupportedToday {
            get {
                return ResourceManager.GetString("Invalid_Game_NoSupportedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日已助力过该好友.
        /// </summary>
        internal static string Invalid_Game_NoSupportToday {
            get {
                return ResourceManager.GetString("Invalid_Game_NoSupportToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此游戏没有实现.
        /// </summary>
        internal static string Invalid_Game_NotImpl {
            get {
                return ResourceManager.GetString("Invalid_Game_NotImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 助力上限了.
        /// </summary>
        internal static string Invalid_Game_SupportMax {
            get {
                return ResourceManager.GetString("Invalid_Game_SupportMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重试.
        /// </summary>
        internal static string Invalid_Game_TryAgain {
            get {
                return ResourceManager.GetString("Invalid_Game_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户积分操作异常.
        /// </summary>
        internal static string Invalid_Integral {
            get {
                return ResourceManager.GetString("Invalid_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重试.
        /// </summary>
        internal static string Invalid_SystemError {
            get {
                return ResourceManager.GetString("Invalid_SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动信息异常.
        /// </summary>
        internal static string OARedEnvelope_ActivityError {
            get {
                return ResourceManager.GetString("OARedEnvelope_ActivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动尚未开始或者活动已经结束啦.
        /// </summary>
        internal static string OARedEnvelope_ActivityTimeError {
            get {
                return ResourceManager.GetString("OARedEnvelope_ActivityTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未关注公众号.
        /// </summary>
        internal static string OARedEnvelope_Follow {
            get {
                return ResourceManager.GetString("OARedEnvelope_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您已经是公众号的老用户啦，只有新用户才能领取红包哦.
        /// </summary>
        internal static string OARedEnvelope_OldUser {
            get {
                return ResourceManager.GetString("OARedEnvelope_OldUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有红包了.
        /// </summary>
        internal static string OARedEnvelope_RedEnvelopeNone {
            get {
                return ResourceManager.GetString("OARedEnvelope_RedEnvelopeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此微信号已经领取过一次，一个微信号只能领取一次哦.
        /// </summary>
        internal static string OARedEnvelope_UserAlreadRecive {
            get {
                return ResourceManager.GetString("OARedEnvelope_UserAlreadRecive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您不满足领取条件.
        /// </summary>
        internal static string OARedEnvelope_UserValidateError {
            get {
                return ResourceManager.GetString("OARedEnvelope_UserValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数错误.
        /// </summary>
        internal static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComplaintsID参数不能为空.
        /// </summary>
        internal static string ParameterError_ComplaintsID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_ComplaintsID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department参数不能为空.
        /// </summary>
        internal static string ParameterError_Department_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_Department_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题{0}为必填项.
        /// </summary>
        internal static string ParameterError_IsRequired {
            get {
                return ResourceManager.GetString("ParameterError_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}不符合规则 的本地化字符串。
        /// </summary>
        internal static string ParameterError_NotConformityRule {
            get {
                return ResourceManager.GetString("ParameterError_NotConformityRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}为不能为空 的本地化字符串。
        /// </summary>
        internal static string ParameterError_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题{0}为不能为0 的本地化字符串。
        /// </summary>
        internal static string ParameterError_NotZero {
            get {
                return ResourceManager.GetString("ParameterError_NotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderID参数不能为空.
        /// </summary>
        internal static string ParameterError_OrderID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_OrderID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题{0}超出可输入的字符长度.
        /// </summary>
        internal static string ParameterError_OverMaxChar {
            get {
                return ResourceManager.GetString("ParameterError_OverMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageID参数不能为空.
        /// </summary>
        internal static string ParameterError_PageID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_PageID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone参数必须为数字类型.
        /// </summary>
        internal static string ParameterError_Phone_IsNumber {
            get {
                return ResourceManager.GetString("ParameterError_Phone_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的手机号已被登记.
        /// </summary>
        internal static string ParameterError_Phone_IsRegisted {
            get {
                return ResourceManager.GetString("ParameterError_Phone_IsRegisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionList参数不能为空.
        /// </summary>
        internal static string ParameterError_QuestionList_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_QuestionList_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionnaireID参数不能为空.
        /// </summary>
        internal static string ParameterError_QuestionnaireID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_QuestionnaireID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffEmail参数不能为空.
        /// </summary>
        internal static string ParameterError_StaffEmail_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_StaffEmail_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID参数不能为空.
        /// </summary>
        internal static string ParameterError_UserID_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_UserID_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPhone参数不能为空.
        /// </summary>
        internal static string ParameterError_UserPhone_NotNull {
            get {
                return ResourceManager.GetString("ParameterError_UserPhone_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的问卷已成功提交.
        /// </summary>
        internal static string Questionnaire_IsAnswered {
            get {
                return ResourceManager.GetString("Questionnaire_IsAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您访问的问卷不存在.
        /// </summary>
        internal static string Questionnaire_NotExist {
            get {
                return ResourceManager.GetString("Questionnaire_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的问卷已过期.
        /// </summary>
        internal static string Questionnaire_Overdue {
            get {
                return ResourceManager.GetString("Questionnaire_Overdue", resourceCulture);
            }
        }
    }
}
