package com.tuhu.springbootmybatis.mapper;

import com.tuhu.springbootmybatis.entity.TTrainEntry;
import com.tuhu.springbootmybatis.vo.TTrainEntryRespGetVO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TTrainEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    int deleteLogicByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int insert(TTrainEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int insertSelective(TTrainEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    TTrainEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int updateByPrimaryKeySelective(TTrainEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_train_entry
     *
     * @mbggenerated Tue Sep 29 18:23:57 CST 2020
     */
    int updateByPrimaryKey(TTrainEntry record);


    /**
     * 运营查询所有报名课程信息
     * @param
     * @return
     */
    List<TTrainEntryRespGetVO> selectEntry();


    /**
     * 定时任务审核报名信息状态
     * @param
     * @return
     */
    int updateEntrySchedule(TTrainEntry entry);

    /**
     * 运营查询课程是否被报名占用
     * @param entry
     * @return
     */
    int selectEntryByCourseId(TTrainEntry entry);
}